DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS dishesofday;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS votes;
DROP SEQUENCE IF EXISTS global_seq;
DROP SEQUENCE IF EXISTS rest_seq;
DROP SEQUENCE IF EXISTS DISH_SEQ;
DROP SEQUENCE IF EXISTS DISHOFDAY_SEQ;

CREATE SEQUENCE GLOBAL_SEQ     START WITH 100000;
CREATE SEQUENCE REST_SEQ       START WITH 200000;
CREATE SEQUENCE DISH_SEQ       START WITH 300000;
CREATE SEQUENCE DISHOFDAY_SEQ  START WITH 0;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  firstname        VARCHAR(255)            NOT NULL,
  lastname         VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL,
  active           BOOLEAN DEFAULT TRUE    NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE REST_SEQ PRIMARY KEY,
  title            VARCHAR(255)            NOT NULL,
  address          VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  site             VARCHAR(255)            NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX restaurants_unique_email_idx ON restaurants (email);

CREATE TABLE dishes
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE DISH_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  price            INTEGER                 NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL,
  restaurant_id    INTEGER                 NOT NULL,
  FOREIGN KEY      (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX dishes_unique_restaurant_name_idx ON dishes (restaurant_id, name);

CREATE TABLE dishesofday
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE DISHOFDAY_SEQ PRIMARY KEY,
  datelunch        DATE  DEFAULT now()     NOT NULL,
  dish_id          INTEGER                 NOT NULL,
  FOREIGN KEY      (dish_id) REFERENCES dishes (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX dishesofday_unique_datelunch_dish_id_idx ON dishesofday (datelunch, dish_id);

CREATE TABLE votes
(
  id               INTEGER IDENTITY  PRIMARY KEY,
  datelunch        DATE  DEFAULT now()     NOT NULL,
  user_id          INTEGER                 NOT NULL,
  restaurant_id    INTEGER                 NOT NULL
);
CREATE UNIQUE INDEX votes_unique_datelunch_user_id_idx ON votes (datelunch, user_id);
